name: Docker Image CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t huangminjian/cenetery-qr-code-image --platform linux/amd64 . 
    - name: docker Login
      run: docker login --username=huangminjian --password=15976244339bb
    - name: Push the Docker image
      run: docker push huangminjian/cenetery-qr-code-image
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "101.33.246.28"
        username: "root"
        password: "huangminjian123Aa"
        port: "22"
        script: ls -a && docker stop cenetery-qr-code-docker && docker rm cenetery-qr-code-docker && docker rmi huangminjian/cenetery-qr-code-image && docker login --username=huangminjian --password=15976244339bb && docker pull huangminjian/cenetery-qr-code-image && docker run -d --name cenetery-qr-code-docker -p 8889:3000 huangminjian/cenetery-qr-code-image /bin/sh -c "cd ./app;npm run dev" 
        
        
        
  

